/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinge_chat_module_login_GetLocalKey */

#ifndef _Included_com_xinge_chat_module_login_GetLocalKey
#define _Included_com_xinge_chat_module_login_GetLocalKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinge_chat_module_login_GetLocalKey
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xinge_chat_module_login_GetLocalKey_getKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
